DROP TABLE IF EXISTS _USER_PROBLEM;

CREATE TABLE _USER_PROBLEM(
    _USER_ID INT NOT NULL,
    PROBLEM_ID INT NOT NULL,
    CODE TEXT NOT NULL,
    FOREIGN KEY (_USER_ID) REFERENCES _USER(_USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (PROBLEM_ID) REFERENCES PROBLEM(PROBLEM_ID) ON DELETE CASCADE
);
