DROP TABLE IF EXISTS _USER;

CREATE TABLE _USER(
    _USER_ID SERIAL,
    USER_TYPE_ID INT NOT NULL,
    FIRST_NAME TEXT NOT NULL,
    LAST_NAME TEXT NOT NULL,
    PHONE TEXT,
    ADDRESS TEXT,
    EMAIL TEXT NOT NULL,
    BORN_DATE DATE,
    PASSWORD TEXT NOT NULL,
    STATUS BOOLEAN DEFAULT true,
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (_USER_ID),
    FOREIGN KEY (USER_TYPE_ID) REFERENCES USER_TYPE(USER_TYPE_ID)
);

--MASTER DATA
INSERT INTO _USER(USER_TYPE_ID, FIRST_NAME, LAST_NAME, PHONE, ADDRESS, EMAIL, BORN_DATE, PASSWORD, STATUS)
VALUES (1, 'Guillermo', 'Peitzner', '1234567890', '123 Main St', 'guillermopeitzner@gmail.com', '1996-12-01', 'password', true);

INSERT INTO _USER(USER_TYPE_ID, FIRST_NAME, LAST_NAME, PHONE, ADDRESS, EMAIL, BORN_DATE, PASSWORD, STATUS)
VALUES (2, 'Alfredo', 'Estrada', '1234567890', '123 Main St', 'alfredoestrada@gmail.com', '1996-12-01', 'password', true);
